### ISSUE TITLE
PHPUnit 1.11 and PHP 8.1 not compatible

### ISSUE THREAD

**Issue by llaville** [pecm/pickling#4]
Hello,

You've introduced a PHP 8.1 platform issue when you've upgraded PHPUnit to 1.11 with commit https://github.com/pecm/pickling/commit/fc4c9c2d64be6dd7fe0cf514e85c564611deca18

Currently on PHP 8.1 platform, we cannot install the package after cloning the repo.

```text
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit[11.1.0, ..., 11.4.x-dev] require php >=8.2 -> your php version (8.1.30) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ^11.1 -> satisfiable by phpunit/phpunit[11.1.0, ..., 11.4.x-dev].
```

I suggest either to : 
- drop support to PHP 8.1
- or keep supporting with this following patch

```text
diff --git a/composer.json b/composer.json
index 06d1e70..f33d240 100644
--- a/composer.json
+++ b/composer.json
@@ -52,7 +52,7 @@
     "nyholm/psr7": "^1.3",
     "php-parallel-lint/php-parallel-lint": "^1.3",
     "phpstan/phpstan": "^1.10",
-    "phpunit/phpunit": "^11.1",
+    "phpunit/phpunit": "^10.5 || ^11.1",
     "psr-mock/http-client-implementation": "^1.0",
     "psy/psysh": "^0.12",
     "roave/security-advisories": "dev-latest",
```

> [!NOTE]
>
> PHPUnit and PHP supported versions : https://phpunit.de/supported-versions.html

**Comment by llaville** [comment]
@flavioheleno Did you still maintain this package ?

**Comment by flavioheleno** [comment]
hey @llaville, sorry for my lack of response, I have no clue why I haven't got back to you before!

Let's relax the requirements and fix the issue.

Thank you for calling me on it!
