### ISSUE TITLE
Http Client suggestion may be changed

### ISSUE THREAD

**Issue by llaville** [pecm/pickling#5]
On your README page we can read 

![github com_pecm_pickling](https://github.com/user-attachments/assets/15e1169e-f99f-4ca1-ae25-463085272c26)

But as the Socket Client is now deprecated, I suggest to replace it by the [cURL client](https://docs.php-http.org/en/latest/clients/curl-client.html)

> The new recommendation should give something like : 

A general suggestion for HTTP Client, using [php-http/curl-client](https://packagist.org/packages/php-http/curl-client) and [nyholm/psr7](https://packagist.org/packages/nyholm/psr7):

```bash
composer require php-http/curl-client nyholm/psr7
```

**Comment by flavioheleno** [comment]
Neither [packagist](https://packagist.org/packages/php-http/socket-client) nor the [repository](https://github.com/php-http/socket-client) shows anything about it being deprecated.

It actually had a [release 2 months ago](https://github.com/php-http/socket-client/releases/tag/2.3.0). Am I missing anything?

**Comment by llaville** [comment]
The deprecations are visible on documentation at https://docs.php-http.org/en/latest/clients.html

**Comment by llaville** [comment]
@flavioheleno Coul you explain your choice of https://packagist.org/packages/kriswallsmith/buzz rather than https://packagist.org/packages/php-http/curl-client (as I've suggested) ?

**Comment by flavioheleno** [comment]
hey @llaville, not in any particular order:

* **buzz** has both a _curl-based_ client and a _stream-based_ client, which makes `ext-curl` fully optional;
* **buzz** has been around longer than **curl-client**;
* **buzz** has a [backwards compatibility promise](https://github.com/kriswallsmith/Buzz?tab=readme-ov-file#backwards-compatibility-promise);
* the fact that **socket-client**'s deprecation notice was _only_ displayed on its website and not on packagist nor its repository is, in my opinion, a poor practice towards users.
